run:
    deadline: 2m
    skip-dirs:
        - build
        - frontend
        - scratch
        - scripts

linters:
    enable-all: true
    disable:
        - containedctx
        - exhaustivestruct
        - exhaustruct
        - nolintlint
        - staticcheck

linters-settings:
    goimports:
        local-prefixes: github.com/multibase-io/multibase
    exhaustive:
        default-signifies-exhaustive: true
    lll:
        tab-width: 8
    tagliatelle:
        case:
            use-field-name: true
            rules:
                json: goCamel
