run:
    deadline: 5m
    skip-dirs:
        - build
        - frontend
        - scratch
        - scripts

linters:
    enable-all: true
    disable:
        - containedctx
        - depguard
        - exhaustivestruct
        - exhaustruct
        - nilnil
        - nolintlint
        - staticcheck

linters-settings:
    gci:
        local-prefixes: github.com/catake-com/multibase
    goimports:
        local-prefixes: github.com/catake-com/multibase
    exhaustive:
        default-signifies-exhaustive: true
    lll:
        tab-width: 8
    tagliatelle:
        case:
            use-field-name: true
            rules:
                json: goCamel
    varnamelen:
        ignore-type-assert-ok: true
        ignore-map-index-ok: true
        ignore-chan-recv-ok: true
        ignore-names:
            - ok
