// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateNewProject(arg1) {
  return window['go']['kafka']['Module']['CreateNewProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['kafka']['Module']['DeleteProject'](arg1);
}

export function State() {
  return window['go']['kafka']['Module']['State']();
}
