// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Brokers(arg1) {
  return window['go']['kafka']['Module']['Brokers'](arg1);
}

export function Close() {
  return window['go']['kafka']['Module']['Close']();
}

export function Connect(arg1) {
  return window['go']['kafka']['Module']['Connect'](arg1);
}

export function Consumers(arg1) {
  return window['go']['kafka']['Module']['Consumers'](arg1);
}

export function CreateNewProject(arg1) {
  return window['go']['kafka']['Module']['CreateNewProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['kafka']['Module']['DeleteProject'](arg1);
}

export function SaveAddress(arg1, arg2) {
  return window['go']['kafka']['Module']['SaveAddress'](arg1, arg2);
}

export function SaveAuthMethod(arg1, arg2) {
  return window['go']['kafka']['Module']['SaveAuthMethod'](arg1, arg2);
}

export function SaveAuthPassword(arg1, arg2) {
  return window['go']['kafka']['Module']['SaveAuthPassword'](arg1, arg2);
}

export function SaveAuthUsername(arg1, arg2) {
  return window['go']['kafka']['Module']['SaveAuthUsername'](arg1, arg2);
}

export function SaveCurrentTab(arg1, arg2) {
  return window['go']['kafka']['Module']['SaveCurrentTab'](arg1, arg2);
}

export function StartTopicConsuming(arg1, arg2, arg3) {
  return window['go']['kafka']['Module']['StartTopicConsuming'](arg1, arg2, arg3);
}

export function State() {
  return window['go']['kafka']['Module']['State']();
}

export function StopTopicConsuming(arg1) {
  return window['go']['kafka']['Module']['StopTopicConsuming'](arg1);
}

export function Topics(arg1) {
  return window['go']['kafka']['Module']['Topics'](arg1);
}
