// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kafka} from '../models';

export function CreateNewProject(arg1:string):Promise<kafka.State>;

export function DeleteProject(arg1:string):Promise<kafka.State>;

export function State():Promise<kafka.State>;
