// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kafka} from '../models';

export function CreateNewProject(arg1:string):Promise<kafka.State>;

export function DeleteProject(arg1:string):Promise<kafka.State>;

export function SaveAddress(arg1:string,arg2:string):Promise<kafka.State>;

export function SaveAuthMethod(arg1:string,arg2:string):Promise<kafka.State>;

export function SaveAuthPassword(arg1:string,arg2:string):Promise<kafka.State>;

export function SaveAuthUsername(arg1:string,arg2:string):Promise<kafka.State>;

export function SaveCurrentTab(arg1:string,arg2:string):Promise<kafka.State>;

export function SaveState():Promise<Error>;

export function State():Promise<kafka.State>;
