// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StopRequest(arg1) {
  return window['go']['main']['App']['StopRequest'](arg1);
}

export function OpenImportPath() {
  return window['go']['main']['App']['OpenImportPath']();
}

export function OpenProtoFile() {
  return window['go']['main']['App']['OpenProtoFile']();
}

export function RefreshProtoDescriptors(arg1, arg2) {
  return window['go']['main']['App']['RefreshProtoDescriptors'](arg1, arg2);
}

export function SelectMethod(arg1) {
  return window['go']['main']['App']['SelectMethod'](arg1);
}

export function SendRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3, arg4);
}
