// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {grpc} from '../models';
import {main} from '../models';

export function RefreshProtoDescriptors(arg1:number,arg2:Array<string>,arg3:Array<string>):Promise<Array<grpc.ProtoTreeNode>|Error>;

export function SelectMethod(arg1:number,arg2:string):Promise<string|Error>;

export function SendRequest(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<string|Error>;

export function StopRequest(arg1:number,arg2:number):Promise<Error>;

export function OpenImportPath():Promise<string|Error>;

export function OpenProtoFile():Promise<main.OpenProtoFileResult|Error>;
