// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenImportPath() {
  return window['go']['main']['App']['OpenImportPath']();
}

export function OpenProtoFile() {
  return window['go']['main']['App']['OpenProtoFile']();
}

export function RefreshProtoDescriptors(arg1, arg2) {
  return window['go']['main']['App']['RefreshProtoDescriptors'](arg1, arg2);
}
