// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {grpc} from '../models';

export function DeleteProject(arg1:string):Promise<grpc.State|Error>;

export function SelectMethod(arg1:string,arg2:string,arg3:string):Promise<grpc.State|Error>;

export function StopRequest(arg1:string,arg2:string):Promise<grpc.State|Error>;

export function CreateNewForm(arg1:string):Promise<grpc.State|Error>;

export function CreateNewProject(arg1:string):Promise<grpc.State|Error>;

export function OpenImportPath(arg1:string):Promise<grpc.State|Error>;

export function RemoveForm(arg1:string,arg2:string):Promise<grpc.State|Error>;

export function SaveCurrentFormID(arg1:string,arg2:string):Promise<grpc.State|Error>;

export function SendRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<grpc.State|Error>;

export function DeleteAllProtoFiles(arg1:string):Promise<grpc.State|Error>;

export function OpenProtoFile(arg1:string):Promise<grpc.State|Error>;

export function RemoveImportPath(arg1:string,arg2:string):Promise<grpc.State|Error>;

export function SaveRequestPayload(arg1:string,arg2:string,arg3:string):Promise<grpc.State|Error>;

export function SaveSplitterWidth(arg1:string,arg2:number):Promise<grpc.State|Error>;

export function SaveAddress(arg1:string,arg2:string,arg3:string):Promise<grpc.State|Error>;

export function State():Promise<grpc.State|Error>;
