// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectMethod(arg1, arg2) {
  return window['go']['grpc']['Module']['SelectMethod'](arg1, arg2);
}

export function SendRequest(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['grpc']['Module']['SendRequest'](arg1, arg2, arg3, arg4, arg5);
}

export function StopRequest(arg1, arg2) {
  return window['go']['grpc']['Module']['StopRequest'](arg1, arg2);
}

export function OpenImportPath() {
  return window['go']['grpc']['Module']['OpenImportPath']();
}

export function OpenProtoFile() {
  return window['go']['grpc']['Module']['OpenProtoFile']();
}

export function RefreshProtoDescriptors(arg1, arg2, arg3) {
  return window['go']['grpc']['Module']['RefreshProtoDescriptors'](arg1, arg2, arg3);
}
