// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHeader(arg1, arg2) {
  return window['go']['grpc']['Module']['AddHeader'](arg1, arg2);
}

export function CreateNewForm(arg1) {
  return window['go']['grpc']['Module']['CreateNewForm'](arg1);
}

export function CreateNewProject(arg1) {
  return window['go']['grpc']['Module']['CreateNewProject'](arg1);
}

export function DeleteAllProtoFiles(arg1) {
  return window['go']['grpc']['Module']['DeleteAllProtoFiles'](arg1);
}

export function DeleteHeader(arg1, arg2, arg3) {
  return window['go']['grpc']['Module']['DeleteHeader'](arg1, arg2, arg3);
}

export function DeleteProject(arg1) {
  return window['go']['grpc']['Module']['DeleteProject'](arg1);
}

export function OpenImportPath(arg1) {
  return window['go']['grpc']['Module']['OpenImportPath'](arg1);
}

export function OpenProtoFile(arg1) {
  return window['go']['grpc']['Module']['OpenProtoFile'](arg1);
}

export function RemoveForm(arg1, arg2) {
  return window['go']['grpc']['Module']['RemoveForm'](arg1, arg2);
}

export function RemoveImportPath(arg1, arg2) {
  return window['go']['grpc']['Module']['RemoveImportPath'](arg1, arg2);
}

export function SaveAddress(arg1, arg2, arg3) {
  return window['go']['grpc']['Module']['SaveAddress'](arg1, arg2, arg3);
}

export function SaveCurrentFormID(arg1, arg2) {
  return window['go']['grpc']['Module']['SaveCurrentFormID'](arg1, arg2);
}

export function SaveHeaders(arg1, arg2, arg3) {
  return window['go']['grpc']['Module']['SaveHeaders'](arg1, arg2, arg3);
}

export function SaveRequestPayload(arg1, arg2, arg3) {
  return window['go']['grpc']['Module']['SaveRequestPayload'](arg1, arg2, arg3);
}

export function SaveSplitterWidth(arg1, arg2) {
  return window['go']['grpc']['Module']['SaveSplitterWidth'](arg1, arg2);
}

export function SaveState() {
  return window['go']['grpc']['Module']['SaveState']();
}

export function SelectMethod(arg1, arg2, arg3) {
  return window['go']['grpc']['Module']['SelectMethod'](arg1, arg2, arg3);
}

export function SendRequest(arg1, arg2, arg3, arg4) {
  return window['go']['grpc']['Module']['SendRequest'](arg1, arg2, arg3, arg4);
}

export function State() {
  return window['go']['grpc']['Module']['State']();
}

export function StopRequest(arg1, arg2) {
  return window['go']['grpc']['Module']['StopRequest'](arg1, arg2);
}
