// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseProject(arg1) {
  return window['go']['handler']['ProjectHandler']['CloseProject'](arg1);
}

export function CreateGRPCProject(arg1) {
  return window['go']['handler']['ProjectHandler']['CreateGRPCProject'](arg1);
}

export function CreateKafkaProject(arg1) {
  return window['go']['handler']['ProjectHandler']['CreateKafkaProject'](arg1);
}

export function CreateKubernetesProject(arg1) {
  return window['go']['handler']['ProjectHandler']['CreateKubernetesProject'](arg1);
}

export function CreateNewProject() {
  return window['go']['handler']['ProjectHandler']['CreateNewProject']();
}

export function CreateThriftProject(arg1) {
  return window['go']['handler']['ProjectHandler']['CreateThriftProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['handler']['ProjectHandler']['DeleteProject'](arg1);
}

export function OpenProject(arg1, arg2) {
  return window['go']['handler']['ProjectHandler']['OpenProject'](arg1, arg2);
}

export function RenameProject(arg1, arg2) {
  return window['go']['handler']['ProjectHandler']['RenameProject'](arg1, arg2);
}

export function SaveCurrentProjectID(arg1) {
  return window['go']['handler']['ProjectHandler']['SaveCurrentProjectID'](arg1);
}

export function State() {
  return window['go']['handler']['ProjectHandler']['State']();
}
