// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['kubernetes']['Module']['Close']();
}

export function Connect(arg1, arg2) {
  return window['go']['kubernetes']['Module']['Connect'](arg1, arg2);
}

export function CreateNewProject(arg1) {
  return window['go']['kubernetes']['Module']['CreateNewProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['kubernetes']['Module']['DeleteProject'](arg1);
}

export function Namespaces(arg1) {
  return window['go']['kubernetes']['Module']['Namespaces'](arg1);
}

export function OverviewData(arg1) {
  return window['go']['kubernetes']['Module']['OverviewData'](arg1);
}

export function ProjectState(arg1) {
  return window['go']['kubernetes']['Module']['ProjectState'](arg1);
}

export function SaveCurrentTab(arg1, arg2) {
  return window['go']['kubernetes']['Module']['SaveCurrentTab'](arg1, arg2);
}

export function SelectNamespace(arg1, arg2) {
  return window['go']['kubernetes']['Module']['SelectNamespace'](arg1, arg2);
}

export function StartPortForwarding(arg1, arg2, arg3, arg4) {
  return window['go']['kubernetes']['Module']['StartPortForwarding'](arg1, arg2, arg3, arg4);
}

export function StopPortForwarding(arg1) {
  return window['go']['kubernetes']['Module']['StopPortForwarding'](arg1);
}

export function WorkloadsPodsData(arg1) {
  return window['go']['kubernetes']['Module']['WorkloadsPodsData'](arg1);
}
