// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kubernetes} from '../models';

export function Close():Promise<void>;

export function Connect(arg1:string,arg2:string):Promise<any>;

export function CreateNewProject(arg1:string):Promise<any>;

export function DeleteProject(arg1:string):Promise<void>;

export function Namespaces(arg1:string):Promise<Array<string>>;

export function OverviewData(arg1:string):Promise<any>;

export function ProjectState(arg1:string):Promise<any>;

export function SaveCurrentTab(arg1:string,arg2:kubernetes.Tab):Promise<any>;

export function SelectNamespace(arg1:string,arg2:string):Promise<any>;

export function WorkloadsPodsData(arg1:string):Promise<any>;
