// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHeader(arg1, arg2) {
  return window['go']['thrift']['Module']['AddHeader'](arg1, arg2);
}

export function CreateNewForm(arg1) {
  return window['go']['thrift']['Module']['CreateNewForm'](arg1);
}

export function CreateNewProject(arg1) {
  return window['go']['thrift']['Module']['CreateNewProject'](arg1);
}

export function DeleteHeader(arg1, arg2, arg3) {
  return window['go']['thrift']['Module']['DeleteHeader'](arg1, arg2, arg3);
}

export function DeleteProject(arg1) {
  return window['go']['thrift']['Module']['DeleteProject'](arg1);
}

export function OpenFilePath(arg1) {
  return window['go']['thrift']['Module']['OpenFilePath'](arg1);
}

export function RemoveForm(arg1, arg2) {
  return window['go']['thrift']['Module']['RemoveForm'](arg1, arg2);
}

export function SaveAddress(arg1, arg2, arg3) {
  return window['go']['thrift']['Module']['SaveAddress'](arg1, arg2, arg3);
}

export function SaveCurrentFormID(arg1, arg2) {
  return window['go']['thrift']['Module']['SaveCurrentFormID'](arg1, arg2);
}

export function SaveHeaders(arg1, arg2, arg3) {
  return window['go']['thrift']['Module']['SaveHeaders'](arg1, arg2, arg3);
}

export function SaveIsMultiplexed(arg1, arg2, arg3) {
  return window['go']['thrift']['Module']['SaveIsMultiplexed'](arg1, arg2, arg3);
}

export function SaveRequestPayload(arg1, arg2, arg3) {
  return window['go']['thrift']['Module']['SaveRequestPayload'](arg1, arg2, arg3);
}

export function SaveSplitterWidth(arg1, arg2) {
  return window['go']['thrift']['Module']['SaveSplitterWidth'](arg1, arg2);
}

export function SaveState() {
  return window['go']['thrift']['Module']['SaveState']();
}

export function SelectFunction(arg1, arg2, arg3) {
  return window['go']['thrift']['Module']['SelectFunction'](arg1, arg2, arg3);
}

export function SendRequest(arg1, arg2, arg3, arg4) {
  return window['go']['thrift']['Module']['SendRequest'](arg1, arg2, arg3, arg4);
}

export function State() {
  return window['go']['thrift']['Module']['State']();
}

export function StopRequest(arg1, arg2) {
  return window['go']['thrift']['Module']['StopRequest'](arg1, arg2);
}
