// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHeader(arg1:string,arg2:string):Promise<any>;

export function CreateNewForm(arg1:string):Promise<any>;

export function CreateNewProject(arg1:string):Promise<any>;

export function DeleteHeader(arg1:string,arg2:string,arg3:string):Promise<any>;

export function DeleteProject(arg1:string):Promise<void>;

export function OpenFilePath(arg1:string):Promise<any>;

export function Project(arg1:string):Promise<any>;

export function RemoveForm(arg1:string,arg2:string):Promise<any>;

export function SaveAddress(arg1:string,arg2:string,arg3:string):Promise<any>;

export function SaveCurrentFormID(arg1:string,arg2:string):Promise<any>;

export function SaveHeaders(arg1:string,arg2:string,arg3:Array<any>):Promise<any>;

export function SaveIsMultiplexed(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function SaveRequestPayload(arg1:string,arg2:string,arg3:string):Promise<any>;

export function SaveSplitterWidth(arg1:string,arg2:number):Promise<any>;

export function SelectFunction(arg1:string,arg2:string,arg3:string):Promise<any>;

export function SendRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<any>;

export function StopRequest(arg1:string,arg2:string):Promise<any>;
