// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {thrift} from '../models';

export function AddHeader(arg1:string,arg2:string):Promise<thrift.Project>;

export function CreateNewForm(arg1:string):Promise<thrift.Project>;

export function CreateNewProject(arg1:string):Promise<thrift.Project>;

export function DeleteHeader(arg1:string,arg2:string,arg3:string):Promise<thrift.Project>;

export function DeleteProject(arg1:string):Promise<Error>;

export function OpenFilePath(arg1:string):Promise<thrift.Project>;

export function Project(arg1:string):Promise<thrift.Project>;

export function RemoveForm(arg1:string,arg2:string):Promise<thrift.Project>;

export function SaveAddress(arg1:string,arg2:string,arg3:string):Promise<thrift.Project>;

export function SaveCurrentFormID(arg1:string,arg2:string):Promise<thrift.Project>;

export function SaveHeaders(arg1:string,arg2:string,arg3:Array<thrift.Header>):Promise<thrift.Project>;

export function SaveIsMultiplexed(arg1:string,arg2:string,arg3:boolean):Promise<thrift.Project>;

export function SaveRequestPayload(arg1:string,arg2:string,arg3:string):Promise<thrift.Project>;

export function SaveSplitterWidth(arg1:string,arg2:number):Promise<thrift.Project>;

export function SelectFunction(arg1:string,arg2:string,arg3:string):Promise<thrift.Project>;

export function SendRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<thrift.Project>;

export function StopRequest(arg1:string,arg2:string):Promise<thrift.Project>;
