// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateGRPCProject(arg1) {
  return window['go']['project']['Module']['CreateGRPCProject'](arg1);
}

export function CreateNewProject() {
  return window['go']['project']['Module']['CreateNewProject']();
}

export function DeleteGRPCProject(arg1) {
  return window['go']['project']['Module']['DeleteGRPCProject'](arg1);
}

export function OpenGRPCProject(arg1, arg2) {
  return window['go']['project']['Module']['OpenGRPCProject'](arg1, arg2);
}

export function RenameGRPCProject(arg1, arg2) {
  return window['go']['project']['Module']['RenameGRPCProject'](arg1, arg2);
}

export function SaveCurrentProjectID(arg1) {
  return window['go']['project']['Module']['SaveCurrentProjectID'](arg1);
}

export function State() {
  return window['go']['project']['Module']['State']();
}

export function CloseProject(arg1) {
  return window['go']['project']['Module']['CloseProject'](arg1);
}
