// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseProject(arg1:string):Promise<any>;

export function CreateGRPCProject(arg1:string):Promise<any>;

export function CreateKafkaProject(arg1:string):Promise<any>;

export function CreateNewProject():Promise<any>;

export function CreateThriftProject(arg1:string):Promise<any>;

export function DeleteProject(arg1:string):Promise<any>;

export function OpenProject(arg1:string,arg2:string):Promise<any>;

export function RenameProject(arg1:string,arg2:string):Promise<any>;

export function SaveCurrentProjectID(arg1:string):Promise<any>;

export function State():Promise<any>;
