// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseProject(arg1) {
  return window['go']['project']['Module']['CloseProject'](arg1);
}

export function CreateGRPCProject(arg1) {
  return window['go']['project']['Module']['CreateGRPCProject'](arg1);
}

export function CreateKafkaProject(arg1) {
  return window['go']['project']['Module']['CreateKafkaProject'](arg1);
}

export function CreateKubernetesProject(arg1) {
  return window['go']['project']['Module']['CreateKubernetesProject'](arg1);
}

export function CreateNewProject() {
  return window['go']['project']['Module']['CreateNewProject']();
}

export function CreateThriftProject(arg1) {
  return window['go']['project']['Module']['CreateThriftProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['project']['Module']['DeleteProject'](arg1);
}

export function OpenProject(arg1, arg2) {
  return window['go']['project']['Module']['OpenProject'](arg1, arg2);
}

export function RenameProject(arg1, arg2) {
  return window['go']['project']['Module']['RenameProject'](arg1, arg2);
}

export function SaveCurrentProjectID(arg1) {
  return window['go']['project']['Module']['SaveCurrentProjectID'](arg1);
}

export function State() {
  return window['go']['project']['Module']['State']();
}
