// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {project} from '../models';

export function OpenProject(arg1:string,arg2:string):Promise<project.State|Error>;

export function CloseProject(arg1:string):Promise<project.State|Error>;

export function CreateGRPCProject(arg1:string):Promise<project.State|Error>;

export function CreateNewProject():Promise<project.State|Error>;

export function CreateThriftProject(arg1:string):Promise<project.State|Error>;

export function DeleteGRPCProject(arg1:string):Promise<project.State|Error>;

export function DeleteThriftProject(arg1:string):Promise<project.State|Error>;

export function RenameProject(arg1:string,arg2:string):Promise<project.State|Error>;

export function SaveCurrentProjectID(arg1:string):Promise<project.State|Error>;

export function State():Promise<project.State|Error>;
