name: Release

on:
    push:
        tags:
            - "*"

jobs:
    build-macos-win:
        runs-on: macos-12
        steps:
            -   uses: actions/setup-go@v4
                with:
                    go-version: '1.20'
            -   uses: actions/setup-node@v3
                with:
                    node-version: '16.19'
            -   uses: maxim-lobanov/setup-xcode@v1
                with:
                    xcode-version: '14.2'
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Install Wails
                run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
            -   name: Import Code-Signing Certificates
                uses: Apple-Actions/import-codesign-certs@v1
                with:
                    keychain-password: ${{ secrets.APPLE_PASSWORD }}
                    p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
                    p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
            -   name: Install macOS Wails deps
                run: brew install mitchellh/gon/gon
            -   name: Build for Mac OS
                run: wails build -platform darwin/universal -o Multibase
            -   name: Sign for Mac OS
                env:
                    APPLE_USERNAME: ${{ secrets.APPLE_USERNAME }}
                    APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
                    APPLICATION_IDENTITY: ${{ secrets.APPLICATION_IDENTITY }}
                run: |
                    export SECRETVARS='$APPLICATION_IDENTITY:$APPLE_USERNAME' && \
                    envsubst "$SECRETVARS" < ./build/darwin/gon-sign.template.json > ./build/darwin/gon-sign.json && \
                    gon -log-level=info ./build/darwin/gon-sign.json
            -   name: Package for Mac OS
                run: |
                    npx create-dmg ./build/bin/Multibase.app --dmg-title=Multibase --overwrite ./build/bin && \
                    mv ./build/bin/Multibase*.dmg ./build/bin/multibase.dmg
            -   name: Notarize for Mac OS
                env:
                    APPLE_USERNAME: ${{ secrets.APPLE_USERNAME }}
                    APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
                run: |
                    export SECRETVARS='$APPLE_USERNAME' && \
                    envsubst "$SECRETVARS" < ./build/darwin/gon-notarize.template.json > ./build/darwin/gon-notarize.json && \
                    gon -log-level=info ./build/darwin/gon-notarize.json
#            -   name: Build for Windows x86
#                run: wails build -platform windows/amd64 -o Multibase_win_x86.exe
#            -   name: Build for Windows ARM
#                run: wails build -platform windows/arm64 -o Multibase_win_arm.exe
            -   name: Release
                uses: softprops/action-gh-release@v1
                with:
                    files: |
                        build/bin/*

#    build-linux-x86:
#        runs-on: ubuntu-20.04
#        steps:
#            -   uses: actions/setup-go@v4
#                with:
#                    go-version: '1.20'
#            -   uses: actions/setup-node@v3
#                with:
#                    node-version: 16
#            -   name: Install packages
#                run: |
#                    sudo apt-get update && \
#                    sudo apt-get install build-essential pkg-config libgtk-3-dev libgtk-3-0 libwebkit2gtk-4.0-dev
#            -   name: Checkout
#                uses: actions/checkout@v2
#            -   name: Install Wails
#                run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
#            -   name: Build for Linux x86
#                run: wails build -platform linux/amd64 -o Multibase_linux_x86
#            -   name: Release
#                uses: softprops/action-gh-release@v1
#                with:
#                    files: |
#                        build/bin/*
