name: Release

on:
    push:
        tags:
            - "*"

jobs:
    build-macos-win:
        runs-on: macos-12
        steps:
            -   uses: actions/setup-go@v3
                with:
                    go-version: 1.18
            -   uses: actions/setup-node@v3
                with:
                    node-version: 16
            -   uses: maxim-lobanov/setup-xcode@v1
                with:
                    xcode-version: latest-stable
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Install Wails
                run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
            -   name: Build for Mac OS
                run: wails build -platform darwin/universal -o Multibase_macos.app
            -   name: Build for Windows x86
                run: wails build -platform windows/amd64 -o Multibase_win_x86.exe
            -   name: Build for Windows ARM
                run: wails build -platform windows/arm64 -o Multibase_win_arm.exe
            -   name: Release
                uses: softprops/action-gh-release@v1
                with:
                    files: |
                        build/bin/Multibase_macos.app
                        build/bin/Multibase_win_x86.exe
                        build/bin/Multibase_win_arm.exe


    build-linux:
        runs-on: ubuntu-22.04
        steps:
            -   uses: actions/setup-go@v3
                with:
                    go-version: 1.18
            -   uses: actions/setup-node@v3
                with:
                    node-version: 16
            -   name: Install packages
                run: sudo apt-get update && sudo apt-get install build-essential pkg-config libgtk-3-dev libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Install Wails
                run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
            -   name: Build for Linux x86
                run: wails build -platform linux/amd64 -o Multibase_linux_x86
            -   name: Build for Linux ARM
                run: wails build -platform linux/arm64 -o Multibase_linux_arm
            -   name: Release
                uses: softprops/action-gh-release@v1
                with:
                    files: |
                        build/bin/Multibase_linux_x86
                        build/bin/Multibase_linux_arm
