name: Release

on:
    push:
        tags:
            - "*"

jobs:
    build:
        strategy:
            matrix:
                build: [
                    { name: Multibase, platform: linux/amd64, os: ubuntu-latest },
                    { name: Multibase, platform: windows/amd64, os: windows-latest },
                    { name: Multibase, platform: darwin/universal, os: macos-latest }
                ]
        runs-on: ${{ matrix.build.os }}
        steps:
            -   uses: actions/checkout@v2
            -   uses: dAppServer/wails-build-action@v2
                with:
                    build-name: ${{ matrix.build.name }}
                    build-platform: ${{ matrix.build.platform }}
                    go-version: 1.18
                    package: true
