name: release

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: macos-12
        steps:
            -   uses: actions/setup-go@v3
                with:
                    go-version: 1.18
            -   uses: actions/setup-node@v3
                with:
                    node-version: 16
            -   uses: maxim-lobanov/setup-xcode@v1
                with:
                    xcode-version: latest-stable
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Install Wails
                run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
            -   name: Build for Mac OS
                run: wails build -platform darwin/universal
            -   name: Build for Windows
                run: wails build -platform windows/amd64
            -   name: Release
                uses: softprops/action-gh-release@v1
                with:
                    files: |
                        build/bin/Multibase.app
                        build/bin/Multibase.exe
